In [1]:
#creating a matrix with output columns based on input vector(N)
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [2]:
#Similar matrix is created using np.vander function in numpy
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix1 = np.vander(x,N,increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [3]:
# Funtion for moving averages
def moving_avg(n,k):
    try:
        i = 0
        moving_averages = []
        while i < len(n) - k + 1:
            this_window = n[i : i + k]
            window_average = sum(this_window) / k
            moving_averages.append(window_average)
            i += 1
        return(moving_averages)
    except Exception as e:
        print("Error : ",e)
        

In [4]:
moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]